name: Bump version
on:
  push:
    paths-ignore:
      - '**/*README.md'
      - '.github/**'
    branches:
      - main
jobs:
  version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release-version: ${{ steps.tag_version.outputs.new_tag }}

  release:
    needs: version
    name: Create Release
    runs-on: macos-latest #ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Version File
        run: echo ${{ needs.version.outputs.release-version }} > internal/version/version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build
        run: make download-dependencies && make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.version.outputs.release-version }}
          body: "# ${{ github.event.pull_request.title }}\n\n${{ github.event.pull_request.body }}"
          files: |
            *.tgz